language: python
sudo: false
install:
- pip install --upgrade pip
- pip install tox
script:
- tox
matrix:
  include: # Specify both TOXENV and python, see https://stackoverflow.com/a/31990486/3109189
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=coveralls-py3
env:
  global:
  - secure: nOmUVus8q8t3Vcc32mL32tVifIqaM/uq2LBH40Vm/QbE/6m67HLETGE6mLR22ARKl9+lixPSCS59Z1THLCd8TjlGUTt72v4+vKeNQR9taAn+r9Q/Wm7SxusoIJNp1mu9kc+ZgA0/p2ZcRAPmFJtruG6f9vATNT+gnJVJor9WCTPueushYb8+PVNY3l1Gm4IeeGPm3UEAW5XF00MJJKaOLq7k2vFKKQkROBjeHroEhX4HNT7bXEz0XcziqOtYkU+U2jBQB0pmR8xY4LWEh6qXWV0OVAznc5dKl4ZPImW1nsTggJtDf+1C3zyrgxzOIu98DtS7jXUzxRaqodErWu7xNsF0qRdoZ/+oRlBTeAQ2zWhboslmfOfH7h35xvR37HQ+tdjD91owsHnpwHFc7601JkfpKQ4tfksbRplQAc0A7jz54hPe+BkOqyYxZuHJwJJj9YR7MHljQj3azewN1zKO6YX40YwL1ej4sCOSiyAhaLn0ZtvkrlGuebCy5Tm1moRUY3QDEolOmrkdJtSkayAQUnEN8mz26JG0e4YM/BWoiCRUIIUopuFYBWGVm+5jAkw97Ao7bEL+KV7Og7rfiJd9kfCFAKOMFeswNJP30aRtv831rW54x8YU2dR9GJRqKSJhC9K2hOfrIrsnm8clx6qP4S/TWHyF0cNXERBJDjlidkY= # ALGOLIA_APPLICATION_ID
  - secure: o8+7flyO0TONDOMIuu/7Ap6mjZOdmXMJvU88vMVyNBHfhKpcgUxhk9P09f8+VN8fxSYZi7OgeYsyEW+CXVUxziklN02DhkG9BYvk52fWbmJBGnyej4TVlPD83yGhq7opZ0K3yFwHGwySrGt+mPJJ9qtBBd2Q1p33UT94o/hYDW920YlHX7D2A3fUe/n6x7Zgzp1Z7mUIU8ytnO3VI0eY+bh7vGETu/looX+SaHJiLHRsa8rM7h/8/90rz9RWrEokVlw2v/gwpQVPcWr0tx1zelmp/o5WFA/ESbh+EwuDS1NHwl8zg0Pq9oo/QCoyIkSA9xxOo5yxOlSdNdSjX0fLME/Z4BNyOvQB9n8IB4YVnafONSc2nSPC8fB0VtppUOdAgkfdycG2WQMcjtzvs4Taib6TIBT/grQmBU1MhUBXBlmNvoP9ntDBFbqNmmvSawbWKALHuZ45Vtqed8qqEmqN/kzgR8QIdV7TNx81QqbVnQTlymabXQuciNB3u/RtTdHC/fLP7PTl1QAG4rqy8TjT3mcPcK+VrxTmXewFQYw9webTUEUbDGiZltASx/I7dJ5j4zb82x1z7UXeMZL1R6ZDsAdT7Hmb24+mEnN+yTrnbOQI6o+amLyrXIvVsaKsibhjqlsLGtvl6mHdqiVYb9LMi4+IroYAB0eCgZZVpae3U70= # ALGOLIA_API_KEY
