language: python
sudo: false
install:
- pip install --upgrade pip
- pip install tox
script:
- tox
python: 3.5
env:
  matrix:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=coveralls-py3
  global:
  - secure: TRHSjKdlpawKMVkSv4j5XOsQxy5Z3KqnOoYLMIOalSCCz/BCgJjxxopOIytzRurDG9zf/xIBigpKSG1WR6tNQ3Y1IHq+AgLEYND4kp5ilr+F0v/66qxGv3w4bdQ2NrbT0GTYXmFPlUsY/v/urdEwCohOaEdLfZCiN1430OxAMr9fTF4xIow6jQutBG0lsJwsiTNlyYJNUO5uKhYURbXodutDNkZ3z7t95Mvw456tGDfhphxdoMNIsrRWtCsLBwyHti/JZ0vy9i4Qrcw/uML2woVdIiqDf0Drh9tiC9KUtqB8R+6PeI8X7DmdHYQlp+udmkA4LUUjO/3XpMChNdaVgN8qebe6k7E8hmxzOWUBauT33XZ+8zXd0nfzgltztDMxTyi4DwXif8O4ITjCLEIiy95FSh0eTLTiXeoVCi3QN78+YxGnJyBWxAInBboE1bBbD29K6YozF4KwGZ2a2NmKJacETSUfSOOPlkhFvb2uWpdfRU/2fKVShStLoYUDockhtKkc3vHbS5rPnuLgy5W5/xbGWnQedpkThYR4F1b40lzgRzvMWMnSjW/sgzhNuLPeHyxYbV14G5Beq5ISW44JVnN68bH26XRar5fGigxH+fEWh8ct8eKkdx0tumz4IcR7BG2kxHwRChgs/FDfLgJkS3bKAdAU24AS5X8lmHUJB94=
  - secure: EOuz268wXtLm/GpPqWla7DeUtQLLqKlcq8PdIR4dE31B6g8+gd4WLYlcKin+OHE1TeJD3iYSk4Xdwwck5gku9XDrsk/87+0STLljb7XOIqWQgn32p3tsnPnFTEKgj/mb+m9bP1YAeAevocmya0D+QzJDPws4d0FgmEj85XOTIAPwN9VcxTYSsU+S48jRJuX9r0A07qFBNhB/+3BPrLr7WmsGn1U8kinrZVGvcooqaiyTFK7uYiXUAuboTUV+AYBrHQerJt+q7r9U2QVBiWTRnp5p8KP0ELvg/8N/PQIscq40jmq0FWDhKKA+SAW9uc9eXLXC+cRhn8s7SlT6YFQV0zFfvlh+0BZpH34JN/lkV+zlbwT2ksayQWS0KcgmqEXIDwzADXv16dp/Y4HSZ2YavmfxlDSwkYwpv0bQnDvbDrd26OEgGZGjshUwbRjBnu1qfHu7Yh5pB/v0eiciBtD/5HvtSj4pPDFJzWB+1vEfRwvP6oQQ9ROFz+Kb2ME9B7tOLk4lpjpUIqyY+aVmaNNnR/4bFAuOyBibhGkNBqgHrKgOdU55ToZCPp1YZEUyxgIgEfUBDW+LlAisnPPbnWQgayjmQgqi7bxilFRbw1u5CTvKpPjZkVGwuYpWAmtDTtS3YKBqT1HU4+fQWgis5hAYd/NQc8MDWYiWa1UUKW1cqms=
